### ISSUE TITLE
Graphs and Daily Variation no longer updating

### ISSUE THREAD

**Issue by Sgauvr** [lionsharecapital/lionshare-ios#8]
Hello,

I have been using and love Lionshare for a few months now and in the last week, for an unknown reason, the graph of each crypto currency no longer updates (the lines have been looking exactly the same for each of the currencies and do not change

On top of this, the % variation also, is not really updating every 24 hours 

Not sure what happened or changed. The issue is on 2 of my phones and I have uninstalled the Lionshare app and re-installed it as a test

Please Help

Simon

**Comment by jorilallo** [comment]
This was an API issue, fixed now

**Comment by Sgauvr** [comment]
Hello Jorilallo,

Thanks for getting back to me, I can confirm that the issue is now resolved,

I can now see all of my coins dipping :)

Thanks for the quick response and resolution
